services:
  mini-langgraph:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    image: mini-langgraph:latest  # 构建后镜像的名称和标签   
    environment:
      APP: mini-langgraph
      TAVILY_API_KEY: ${TAVILY_API_KEY}
      DASHSCOPE_API_KEY: ${DASHSCOPE_API_KEY}
      OLLAMA_BASE_URL: http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default  
    volumes:
      - "~/.ssh:/root/.ssh:ro" # 挂载宿主机的ssh配置文件，方便推拉代码（只读）
      - "/etc/localtime:/etc/localtime:ro" # 挂载宿主机时间到容器
      - ".:/root/mini-langgraph"
    working_dir: /root/mini-langgraph
    # sleep infinity 用于保持容器运行，否则 vscode 无法进入容器，建议写在 .devcontainer/docker-compose.yml 文件中
    command: sleep infinity

# -- 网络名称，用于容器间通信
networks:
  default:
    name: mini-langgraph-network
